version: '3.7'

services:
  mysql:
    container_name: adm_videos_mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=adm_videos
    ports:
      - "3306:3306"
    networks:
      - adm_videos_network

networks:
  adm_videos_network: